name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: GoReleaser Action
      # You may pin to the exact commit or the version.
      # uses: goreleaser/goreleaser-action@8708f5739924b7f505108288dbb66723d4dfe2ae
      uses: goreleaser/goreleaser-action@v2.1.1
      with:
        # Arguments to pass to GoReleaser
        args: goreleaser release --skip-publish --snapshot --rm-dist
    - name: Remove dist
      run: cd dist && rm -rf $(ls | find . -maxdepth 1 -type d -printf '%f\n') || rm config.yaml

    # Runs a set of commands using the runners shell
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: dist/*